language: c
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-7
    packages:
      - clang-tidy-7
      - clang-format-7

script:
  - ./ci_run.sh

notifications:
  email: false
